language: cpp

os:
    - linux
    - osx

install:
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
          sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
       && sudo add-apt-repository --yes ppa:beineri/opt-qt551
       && sudo apt-get update -qq
       && sudo apt-get install -qq qt55base libmediainfo-dev
        ;
      else
          brew update > /dev/null
       && brew tap homebrew/versions
       && brew install qt55
       && chmod -R 755 /usr/local/opt/qt55/*
       && npm install -g appdmg
        ;
      fi     

script:
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
          . /opt/qt55/bin/qt55-env.sh
        ;
      else
          export QTDIR="/usr/local/opt/qt55"
       && export PATH="$QTDIR/bin:$PATH"
        ;
      fi
    - qmake -v
    - qmake
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
          make -j2
        ;
      else
          make -j2
       && make appdmg
        ;
      fi
    - export VERSION=`scripts/version.sh`
    - export DST_DIR=../qnapi-$VERSION
    - mkdir $DST_DIR
    - cp -rv * $DST_DIR
    - find $DST_DIR | grep .git | xargs rm -fr
    - rm -fr $DST_DIR/deps/libmediainfo
    - rm -fr $DST_DIR/win32/content/7za.exe
    - rm -fr $DST_DIR/macx/content/7za
    - rm -fr $DST_DIR/macx/QNapi*app
    - rm -fr $DST_DIR/macx/QNapi*dmg
    - tar -zcvf qnapi-$VERSION.tar.gz $DST_DIR
    - rm -fr $DST_DIR

