install:
  - set QTDIR=C:\Qt\5.7\mingw53_32
  - set MINGW=C:\Qt\Tools\mingw530_32
  - set NSIS="C:\Program Files (x86)\NSIS"
  - set PATH=%PATH%;%MINGW%\bin;%QTDIR%\bin;%NSIS%
  - appveyor-retry cinst nsis -y -version 2.51
  - appveyor-retry cinst 7zip.commandline -y -x86
  - appveyor DownloadFile "http://nsis.sourceforge.net/mediawiki/images/archive/1/18/20140806212030!NsProcess.zip" -FileName NsProcess.zip
  - 7z e -o"C:\Program Files (x86)\NSIS\Include" NsProcess.zip Include\*.nsh
  - 7z e -o"C:\Program Files (x86)\NSIS\Plugins" NsProcess.zip Plugin\*.dll
  - git submodule update --init --recursive
build_script:
  - qmake qnapi.pro
  - mingw32-make -j4
  - mingw32-make install
  - makensis win32/QNapi-setup.nsi
  - scripts/version.bat > ver.txt
  - set /p VERSION=<ver.txt
  - rem ver.txt
  - cd win32
  - rename out QNapi
  - cd QNapi
  - copy /y nul qnapi.ini
  - cd ..
  - 7z a -tzip QNapi-%VERSION%-portable.zip QNapi 
  - cd ..
artifacts:
  - path: win32\QNapi*zip
  - path: win32\QNapi*exe
deploy:
  provider: GitHub
  description: This is latest snapshot release. Be careful - it may not be stable!
  auth_token:
    secure: W8Vjs744iJ2Tb6DWml0XY8LAOyj3FXlvA9ZhAlaIxCAYhjAL3e7yolizmaoLSlhy 
  artifact: /QNapi.*/
  force_update: true
  on:
    appveyor_repo_tag: true

